// Build script for Vercel (simplified - no API keys needed)
const fs = require('fs');
const path = require('path');

// Read the original config.js
const configPath = path.join(__dirname, 'config.js');
let configContent = fs.readFileSync(configPath, 'utf8');

// Create a new config with actual values (no API keys needed)
const newConfigContent = `// Configuration file for environment variables
// This file is auto-generated by Vercel build process

window.APP_CONFIG = {
    // Feature flags
    ENABLE_AUDIO: true,
    ENABLE_ANIMATIONS: true,
    
    // Debug settings (set to false in production)
    DEBUG_MODE: false
};
`;

// Write the new config
fs.writeFileSync(configPath, newConfigContent);

console.log('✅ Configuration updated successfully');
